import NavBar from './Nav-Bar/NavBar'
import Footer from './Footer/Footer'
import Head from "next/head";
import { useState } from 'react';

const Layout = ({children},props) =>{

    const [isLogged, setLogged] = useState(false);

    return (
      <div>
        <Head>
          <title>ESGTS-CONNECTIONS</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="icon"
            href="https://siesgt.ipsantarem.pt/esgt/imagens/pageicon"
          />
        </Head>

        <NavBar isLogged={isLogged} />

        <main>{children}</main>

        <Footer />
      </div>
    );

}

export default Layout